version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    ignore:
      - dependency-name: 'eslint'
        update-types:
          - 'version-update:semver-major'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'security'
    groups:
      prod-dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'
